/* GENERATED by scripts/generate-abi.py - DO NOT EDIT.
 *
 * Versioned PKCS#11 ABI tables derived from the byte-locked
 * headers in spec/vendor/ (see spec/sources.lock.json).
 * Regenerate: python3 scripts/generate-abi.py
 *
 * Constant VALUES are intentionally not duplicated here; they
 * stay single-sourced in the pinned headers. This file carries
 * generated structure: counts, versions, and function order.
 */
#ifndef HASKOKI_ABI_GENERATED_H
#define HASKOKI_ABI_GENERATED_H

/* Function counts per interface. */
#define HASKOKI_ABI_COUNT_240 68
#define HASKOKI_ABI_COUNT_300 92
#define HASKOKI_ABI_COUNT_310 92
#define HASKOKI_ABI_COUNT_320 104

/* Interface versions. */
#define HASKOKI_ABI_240_MAJOR 2
#define HASKOKI_ABI_240_MINOR 40
#define HASKOKI_ABI_300_MAJOR 3
#define HASKOKI_ABI_300_MINOR 0
#define HASKOKI_ABI_310_MAJOR 3
#define HASKOKI_ABI_310_MINOR 1
#define HASKOKI_ABI_320_MAJOR 3
#define HASKOKI_ABI_320_MINOR 2

/* Standard interface name (spec 3.1 section 5.4.6 example). */
#define HASKOKI_ABI_INTERFACE_NAME "PKCS 11"

/* Number of versioned interfaces served via C_GetInterface. */
#define HASKOKI_ABI_INTERFACE_COUNT 3

/* HASKOKI_FOREACH_240(M) (68 entries, pinned order). */
#define HASKOKI_FOREACH_240(M) \
  M(C_Initialize) \
  M(C_Finalize) \
  M(C_GetInfo) \
  M(C_GetFunctionList) \
  M(C_GetSlotList) \
  M(C_GetSlotInfo) \
  M(C_GetTokenInfo) \
  M(C_GetMechanismList) \
  M(C_GetMechanismInfo) \
  M(C_InitToken) \
  M(C_InitPIN) \
  M(C_SetPIN) \
  M(C_OpenSession) \
  M(C_CloseSession) \
  M(C_CloseAllSessions) \
  M(C_GetSessionInfo) \
  M(C_GetOperationState) \
  M(C_SetOperationState) \
  M(C_Login) \
  M(C_Logout) \
  M(C_CreateObject) \
  M(C_CopyObject) \
  M(C_DestroyObject) \
  M(C_GetObjectSize) \
  M(C_GetAttributeValue) \
  M(C_SetAttributeValue) \
  M(C_FindObjectsInit) \
  M(C_FindObjects) \
  M(C_FindObjectsFinal) \
  M(C_EncryptInit) \
  M(C_Encrypt) \
  M(C_EncryptUpdate) \
  M(C_EncryptFinal) \
  M(C_DecryptInit) \
  M(C_Decrypt) \
  M(C_DecryptUpdate) \
  M(C_DecryptFinal) \
  M(C_DigestInit) \
  M(C_Digest) \
  M(C_DigestUpdate) \
  M(C_DigestKey) \
  M(C_DigestFinal) \
  M(C_SignInit) \
  M(C_Sign) \
  M(C_SignUpdate) \
  M(C_SignFinal) \
  M(C_SignRecoverInit) \
  M(C_SignRecover) \
  M(C_VerifyInit) \
  M(C_Verify) \
  M(C_VerifyUpdate) \
  M(C_VerifyFinal) \
  M(C_VerifyRecoverInit) \
  M(C_VerifyRecover) \
  M(C_DigestEncryptUpdate) \
  M(C_DecryptDigestUpdate) \
  M(C_SignEncryptUpdate) \
  M(C_DecryptVerifyUpdate) \
  M(C_GenerateKey) \
  M(C_GenerateKeyPair) \
  M(C_WrapKey) \
  M(C_UnwrapKey) \
  M(C_DeriveKey) \
  M(C_SeedRandom) \
  M(C_GenerateRandom) \
  M(C_GetFunctionStatus) \
  M(C_CancelFunction) \
  M(C_WaitForSlotEvent)

/* HASKOKI_FOREACH_300_NEW(M) (24 entries, pinned order). */
#define HASKOKI_FOREACH_300_NEW(M) \
  M(C_GetInterfaceList) \
  M(C_GetInterface) \
  M(C_LoginUser) \
  M(C_SessionCancel) \
  M(C_MessageEncryptInit) \
  M(C_EncryptMessage) \
  M(C_EncryptMessageBegin) \
  M(C_EncryptMessageNext) \
  M(C_MessageEncryptFinal) \
  M(C_MessageDecryptInit) \
  M(C_DecryptMessage) \
  M(C_DecryptMessageBegin) \
  M(C_DecryptMessageNext) \
  M(C_MessageDecryptFinal) \
  M(C_MessageSignInit) \
  M(C_SignMessage) \
  M(C_SignMessageBegin) \
  M(C_SignMessageNext) \
  M(C_MessageSignFinal) \
  M(C_MessageVerifyInit) \
  M(C_VerifyMessage) \
  M(C_VerifyMessageBegin) \
  M(C_VerifyMessageNext) \
  M(C_MessageVerifyFinal)

/* HASKOKI_FOREACH_320_NEW(M) (12 entries, pinned order). */
#define HASKOKI_FOREACH_320_NEW(M) \
  M(C_EncapsulateKey) \
  M(C_DecapsulateKey) \
  M(C_VerifySignatureInit) \
  M(C_VerifySignature) \
  M(C_VerifySignatureUpdate) \
  M(C_VerifySignatureFinal) \
  M(C_GetSessionValidationFlags) \
  M(C_AsyncComplete) \
  M(C_AsyncGetID) \
  M(C_AsyncJoin) \
  M(C_WrapKeyAuthenticated) \
  M(C_UnwrapKeyAuthenticated)

#endif /* HASKOKI_ABI_GENERATED_H */
