{- | Shared deterministic generators for the property suites.

The LCG and delta-sequence corpus extend the hand-rolled 'genSeq'
precedent (tests/model/TransitionSpec.hs:194-219). QuickCheck
properties run with fixed replay seeds ('propWith') and 'PROP_CASES'
counts, so every run is deterministic.
-}
module Gen
  ( lcgNext
  , lcgBytes
  , genSeq
  , propCases
  , propWith
  , permitOps
  , qcBytes
  , maxChunks
  , chunking
  ) where

import Data.Bits (shiftR)
import qualified Data.ByteString as BS
import Data.ByteString (ByteString)
import Data.List (sort)
import Data.Word (Word64, Word8)
import System.Environment (lookupEnv)
import Text.Read (readMaybe)
import Test.Tasty (TestName, TestTree, localOption)
import Test.Tasty.QuickCheck
  ( Gen
  , Property
  , QuickCheckReplay (QuickCheckReplayLegacy)
  , QuickCheckTests (QuickCheckTests)
  , arbitrary
  , choose
  , testProperty
  , vectorOf
  )

import Haskoki.Outcome (DeltaOp (..))
import Haskoki.Registry (Operation (..))
import Haskoki.Types (Generation (..), ObjectId (..), SessionId (..))

-- | Next LCG value (Numerical Recipes constants, as in the precedent).
lcgNext :: Word64 -> Word64
lcgNext s = s * 6364136223846793005 + 1442695040888963407

-- | N deterministic bytes from a seed (high bits; LCG low bits are weak).
lcgBytes :: Word64 -> Int -> ByteString
lcgBytes seed n = BS.pack (take n (map wordByte (iterate lcgNext seed)))
  where
    wordByte :: Word64 -> Word8
    wordByte w = fromIntegral (w `shiftR` 32)

-- | One delta op drawn from the generator state (precedent copy).
genOp :: Word64 -> (DeltaOp, Word64)
genOp s0 =
  let s1 = lcgNext s0
      s2 = lcgNext s1
      pick = fromIntegral (s1 `mod` 5) :: Int
      sid = SessionId (1 + fromIntegral (s2 `mod` 3))
      oid = ObjectId (1 + fromIntegral (s2 `mod` 5))
      gen = Generation (1 + fromIntegral ((s2 `div` 7) `mod` 4))
  in case pick of
    0 -> (DeltaTouchSession sid, s2)
    1 -> (DeltaCloseSession sid, s2)
    2 -> (DeltaBumpGeneration sid gen, s2)
    3 -> (DeltaCreateObject oid, s2)
    _ -> (DeltaDestroyObject oid, s2)

-- | A deterministic op sequence of the requested length from a seed.
genSeq :: Word64 -> Int -> [DeltaOp]
genSeq seed n = go seed n []
  where
    go :: Word64 -> Int -> [DeltaOp] -> [DeltaOp]
    go _ 0 acc = reverse acc
    go s k acc = let (op, s') = genOp s in go s' (k - 1) (op : acc)

-- | Case-count knob: PROP_CASES, default 100 (fast), CI/high 1000.
propCases :: IO Int
propCases = do
  mtxt <- lookupEnv "PROP_CASES"
  pure (parseCount mtxt)
  where
    parseCount :: Maybe String -> Int
    parseCount mtxt = case mtxt >>= readMaybe of
      Just k | k > 0 -> k
      _ -> 100

-- | A QuickCheck property with a fixed replay seed and case count.
propWith :: TestName -> Int -> Int -> Property -> TestTree
propWith name seed count prop =
  localOption (QuickCheckTests count) $
    localOption (QuickCheckReplayLegacy seed) $
      testProperty name prop

-- | The six permit-bit operations (Codec.hs permitBits assignment).
permitOps :: [Operation]
permitOps = [OpSign, OpVerify, OpEncrypt, OpDecrypt, OpSignRecover, OpVerifyRecover]

-- | A generated byte string of length 0..hi.
qcBytes :: Int -> Gen ByteString
qcBytes hi = do
  n <- choose (0, hi)
  BS.pack <$> vectorOf n arbitrary

-- | Documented maximum chunk count for streaming laws.
maxChunks :: Int
maxChunks = 8

-- | A valid-by-construction chunking: exactly j chunks (possibly
-- empty) that always concatenate to the input.
chunking :: Word64 -> Int -> ByteString -> [ByteString]
chunking seed j bs =
  let len = BS.length bs
      cutVals = take (j - 1) (map cutAt (iterate lcgNext seed))
      cuts = sort cutVals
      bounds = 0 : cuts ++ [len]
  in zipWith takeDrop bounds (drop 1 bounds)
  where
    cutAt :: Word64 -> Int
    cutAt s = fromIntegral (s `mod` fromIntegral (BS.length bs + 1))
    takeDrop :: Int -> Int -> ByteString
    takeDrop a b = BS.take (b - a) (BS.drop a bs)
