#!/usr/bin/env python3
"""Generate the attribute/class/key-type catalog from byte-locked headers.

Reads:
  spec/sources.lock.json          byte lock (the single input header)
  spec/vendor/pkcs11.h         pinned latchset public-domain header
                                  (IDs + aliases)
  spec/attributes.json            existing file (promoted rows are
                                  PRESERVED; see generate-mechanisms.py for
                                  the promotion rule, shared here)

Writes (deterministic bytes, no timestamps):
  spec/attributes.json            158 CKA + 13 CKO + 67 CKK canonical
                                  entries (160/13/69 names with aliases),
                                  sorted by (value, name), plus the
                                  template_rules block (the reviewed enforcement subset)

STDLIB ONLY. Run on HOST python3 from anywhere:
  python3 scripts/generate-attributes.py

Catalog entry != enforcement: generated rows carry value_type
"unreviewed" and applies_to "unreviewed". Review promotes the enforced
subset (per-class required/forbidden/type rules with negative tests);
this generator preserves promoted rows by canonical name and only
verifies their header-derived fields.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import hdr_parse  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SPEC = REPO / "spec"
ATTR_PATH = SPEC / "attributes.json"

# The single locked source (spec/sources.lock.json): every row cites it.
SOURCE_ID, SOURCE_PATH = hdr_parse.selected_header()

GENERATED_NOTE_PREFIX = "Catalog-only (generator note):"

# Template rules: the IN-REPO-REVIEWED subset. Each rule cites
# the implementation + tests that ground it. This table is the single source,
# emitted to attributes.json (template_rules) and to
# core/Haskoki/Attribute/Generated.hs (generatedTemplateRules, enforced
# by Haskoki.Object.checkRules at the strict keygen/pairgen paths).
# Full base-spec required/forbidden tables need the OASIS prose, which
# is not vendored: see spec/source-issues.json GAP-TEMPLATES (named gap, never
# invented). Forbidden lists stay empty until prose-grounds exist;
# value-context forbiddens (wrong class/key-type, pair disagreements,
# malformed values) reject as inconsistent via the keygen paths and are
# pinned by TemplateRulesSpec.
TEMPLATE_RULES = [
    {"class": "CKO_SECRET_KEY", "key_type": "CKK_AES",
     "required": ["CKA_CLASS", "CKA_VALUE_LEN"],
     "forbidden": ["CKA_ENCAPSULATE", "CKA_DECAPSULATE"],
     "notes": "AES keygen: VALUE_LEN required; PQC wrap flags forbidden "
              "(planGenerateKey, KeyManagementSpec caseAesKeygen)."},
    {"class": "CKO_PUBLIC_KEY", "key_type": "CKK_EC",
     "required": ["CKA_CLASS", "CKA_EC_PARAMS"], "forbidden": [],
     "notes": "EC pair: EC_PARAMS required in the public template "
              "(ecCurveOf, KeyManagementSpec caseEcKeypair)."},
    {"class": "CKO_PUBLIC_KEY", "key_type": "CKK_RSA",
     "required": ["CKA_CLASS", "CKA_MODULUS_BITS"], "forbidden": [],
     "notes": "RSA pair: MODULUS_BITS required in the public "
              "template (rsaBitsOf)."},
    {"class": "CKO_SECRET_KEY", "key_type": "CKK_HOTP",
     "required": ["CKA_CLASS", "CKA_VALUE_LEN"], "forbidden": [],
     "notes": "HOTP keygen: VALUE_LEN required "
              "(planGenerateKey, RecipeOtpSpec caseKeygenPlan)."},
    # No ML-KEM rule: CKA_DERIVE defaults FALSE (not absent) on
    # KEM pairs (kemNoDerive), and a forbidden flag may never be
    # stored (presence-based re-validation would poison it).
]

HS_PATH = REPO / "core" / "Haskoki" / "Attribute" / "Generated.hs"

HS_PREAMBLE = '''{- | Generated attribute inventory and template rules.

GENERATED by @scripts/generate-attributes.py@ from the byte-locked
headers (identity) and the reviewed @TEMPLATE_RULES@ table (rules); do
not edit by hand. Re-run the generator to refresh.

Class, key-type and attribute rows carry numeric ids so production
code never hand-types them; 'Haskoki.Object.checkRules' enforces
'generatedTemplateRules' at the strict keygen/pairgen template paths.
The attribute inventory lets the standard-surface FFI resolve
caller @CKA_*@ ids to names without hand-typed numerics.
-}
{-# LANGUAGE OverloadedStrings #-}
module Haskoki.Attribute.Generated
  ( generatedAttributes
  , generatedClasses
  , generatedKeyTypes
  , generatedTemplateRules
  , attributeIdByName
  , attributeNameById
  , classIdByName
  , keyTypeIdByName
  , classNameById
  , keyTypeNameById
  , mustClassId
  , mustKeyTypeId
  ) where

import Data.Text (Text)
import Data.Word (Word64)
'''


def fail(msg):
    print(f"generate-attributes: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def fmt_id(value):
    return "0x%08x" % value


def source_refs(entry, provenance):
    name = entry["name"]
    if name not in provenance:
        fail(f"{name}: canonical spelling not defined in {SOURCE_PATH}")
    if provenance[name]["value"] != entry["value"]:
        fail(f"{name}: canonical value disagrees with {SOURCE_PATH}")
    return [{"section": f"pkcs11.h:{name}",
             "source_id": SOURCE_ID}]


def generated_attr(entry, provenance, kind):
    name = entry["name"]
    row = {
        "numeric_id": fmt_id(entry["value"]),
        "canonical_name": name,
        "aliases": list(entry["aliases"]),
        "source_refs": source_refs(entry, provenance),
        "notes": ("Catalog-only (generator note): identity from the "
                  "byte-locked headers; semantics unreviewed, no "
                  "template enforcement."),
    }
    if kind == "attribute":
        row["value_type"] = "unreviewed"
        row["applies_to"] = "unreviewed"
    return row


def is_promoted(old):
    if not old.get("notes", "").startswith(GENERATED_NOTE_PREFIX):
        return True
    if old.get("value_type", "unreviewed") != "unreviewed":
        return True
    if old.get("applies_to", "unreviewed") != "unreviewed":
        return True
    return False


def verify_preserved(old, entry, provenance):
    name = entry["name"]
    if old.get("numeric_id") != fmt_id(entry["value"]):
        fail(f"{name}: preserved numeric_id {old.get('numeric_id')} != "
             f"header {fmt_id(entry['value'])}")
    if sorted(old.get("aliases", [])) != sorted(entry["aliases"]):
        fail(f"{name}: preserved aliases drift (review, do not silently "
             f"rewrite)")
    want_refs = [{"section": f"pkcs11.h:{name}",
                  "source_id": SOURCE_ID}]
    if old.get("source_refs") != want_refs:
        fail(f"{name}: preserved source_refs drift (review, do not "
             f"silently rewrite)")
    return old


def build_block(old_rows, entries, provenance, kind):
    out = []
    for e in entries:
        if e["name"] in old_rows and is_promoted(old_rows[e["name"]]):
            out.append(verify_preserved(old_rows[e["name"]], e, provenance))
        else:
            out.append(generated_attr(e, provenance, kind))
    dropped = sorted(set(old_rows) - {e["name"] for e in entries})
    if dropped:
        fail(f"existing {kind} rows vanished from headers: {dropped}")
    return [{k: m[k] for k in sorted(m)} for m in out]


def hs_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def hs_text_list(names):
    return "[" + ", ".join(f'"{hs_escape(n)}"' for n in names) + "]"


def render_hs(attrs, classes, key_types):
    lines = [HS_PREAMBLE.rstrip("\n")]
    for title, entries, fname in (
            ("Attribute inventory", attrs, "generatedAttributes"),
            ("Class inventory", classes, "generatedClasses"),
            ("Key-type inventory", key_types, "generatedKeyTypes")):
        lines.append("")
        lines.append(f"-- | {title}: @(numeric id, canonical name, aliases)@.")
        lines.append(f"{fname} :: [(Word64, Text, [Text])]")
        rows = []
        for e in entries:
            rows.append(f'(0x{e["value"]:x}, "{hs_escape(e["name"])}", '
                        f'{hs_text_list(e["aliases"])})')
        lines.append(f"{fname} =")
        lines.append("  [ " + rows[0])
        for r in rows[1:]:
            lines.append("  , " + r)
        lines.append("  ]")
    lines.append("")
    lines.append("-- | Template rules: @(class, key type, required, forbidden)@.")
    lines.append("generatedTemplateRules :: [(Text, Maybe Text, [Text], [Text])]")
    lines.append("generatedTemplateRules =")
    rrows = []
    for r in TEMPLATE_RULES:
        kt = f'Just "{hs_escape(r["key_type"])}"' if r["key_type"] else "Nothing"
        rrows.append(f'("{hs_escape(r["class"])}", {kt}, '
                     f'{hs_text_list(r["required"])}, {hs_text_list(r["forbidden"])})')
    lines.append("  [ " + rrows[0])
    for r in rrows[1:]:
        lines.append("  , " + r)
    lines.append("  ]")
    lines.append("")
    lines.append("attributeIdByName :: Text -> Maybe Word64")
    lines.append("attributeIdByName name = lookup name [(n, w) | (w, n, _) <- generatedAttributes]")
    lines.append("")
    lines.append("attributeNameById :: Word64 -> Maybe Text")
    lines.append("attributeNameById w = lookup w [(w', n) | (w', n, _) <- generatedAttributes]")
    lines.append("")
    lines.append("classIdByName :: Text -> Maybe Word64")
    lines.append("classIdByName name = lookup name [(n, w) | (w, n, _) <- generatedClasses]")
    lines.append("")
    lines.append("keyTypeIdByName :: Text -> Maybe Word64")
    lines.append("keyTypeIdByName name = lookup name [(n, w) | (w, n, _) <- generatedKeyTypes]")
    lines.append("")
    lines.append("classNameById :: Word64 -> Maybe Text")
    lines.append("classNameById w = lookup w [(w', n) | (w', n, _) <- generatedClasses]")
    lines.append("")
    lines.append("keyTypeNameById :: Word64 -> Maybe Text")
    lines.append("keyTypeNameById w = lookup w [(w', n) | (w', n, _) <- generatedKeyTypes]")
    lines.append("")
    lines.append("mustClassId :: Text -> Word64")
    lines.append('mustClassId name = case classIdByName name of')
    lines.append('  Just w -> w')
    lines.append('  Nothing -> error ("mustClassId: unknown " ++ show name)')
    lines.append("")
    lines.append("mustKeyTypeId :: Text -> Word64")
    lines.append('mustKeyTypeId name = case keyTypeIdByName name of')
    lines.append('  Just w -> w')
    lines.append('  Nothing -> error ("mustKeyTypeId: unknown " ++ show name)')
    return "\n".join(lines) + "\n"


def main():
    tables, provenance = hdr_parse.catalog_tables()
    old = {"attributes": {}, "classes": {}, "key_types": {}}
    if ATTR_PATH.exists():
        try:
            data = json.loads(ATTR_PATH.read_text())
        except Exception as e:  # noqa: BLE001 - reported, not hidden
            fail(f"cannot parse {ATTR_PATH}: {e}")
        for block in ("attributes", "classes", "key_types"):
            for m in data.get(block, []):
                old[block][m["canonical_name"]] = m
    attrs = build_block(old["attributes"], tables["CKA_"],
                        provenance, "attribute")
    classes = build_block(old["classes"], tables["CKO_"],
                          provenance, "class")
    key_types = build_block(old["key_types"], tables["CKK_"],
                            provenance, "key_type")
    # Template rules are generator-owned (TEMPLATE_RULES above);
    # every cited name must exist in the tables just built.
    known_cka = {m["canonical_name"] for m in attrs}
    known_cko = {m["canonical_name"] for m in classes}
    known_ckk = {m["canonical_name"] for m in key_types}
    for rule in TEMPLATE_RULES:
        if rule["class"] not in known_cko:
            fail(f"template rule references unknown {rule['class']}")
        if rule["key_type"] is not None and rule["key_type"] not in known_ckk:
            fail(f"template rule references unknown {rule['key_type']}")
        for key in ("required", "forbidden"):
            for name in rule[key]:
                if name not in known_cka:
                    fail(f"template rule references unknown {name}")
        if set(rule["required"]) & set(rule["forbidden"]):
            fail(f"template rule {rule['class']}/{rule['key_type']}: "
                 f"required/forbidden overlap")
    doc = {
        "attributes": attrs,
        "classes": classes,
        "key_types": key_types,
        "template_rules": [{k: r[k] for k in sorted(r)}
                           for r in TEMPLATE_RULES],
        "schema_version": 1,
        "status": "generated-source-of-truth",
        "provenance": ("Identity (numeric_id, aliases, "
                       "source_refs) generated from the byte-locked "
                       "header; template_rules is the generator-owned "
                       "reviewed subset (each rule cites its in-repo "
                       "source), enforced by Haskoki.Object.checkRules. "
                       "Full base-spec tables need the OASIS prose (not "
                       "vendored): see source-issues.json GAP-TEMPLATES."),
    }
    ATTR_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    HS_PATH.parent.mkdir(parents=True, exist_ok=True)
    HS_PATH.write_text(render_hs(tables["CKA_"], tables["CKO_"], tables["CKK_"]))
    print(f"generate-attributes: {len(attrs)} attributes, "
          f"{len(classes)} classes, {len(key_types)} key types, "
          f"{len(TEMPLATE_RULES)} template rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
