"""Shared renderer: the real-executable mechanism catalog.

Reads spec/mechanisms.json; selects rows whose support.real is
"tested" (the normative engine-supported set for the standard C
surface); renders cbits/mech_catalog.inc, consumed by
cbits/standard_surface.c for C_GetMechanismList/C_GetMechanismInfo.

Row order is ascending numeric id (deterministic bytes). Flag cells
are CKF_* macro expressions resolved against the pinned
spec/vendor headers at C compile time -- the C build fails
loudly if a JSON flag name is not a real macro, so no flag spelling
here can drift from the headers.

STDLIB ONLY. Imported by scripts/generate-mechanisms.py (writes the
file) and scripts/check-mechanisms.py (byte-compares it).
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MECH_PATH = REPO / "spec" / "mechanisms.json"
INC_PATH = REPO / "cbits" / "mech_catalog.inc"

HEADER = """/* GENERATED by scripts/generate-mechanisms.py from spec/mechanisms.json
 * (support.real == "tested" rows, ascending numeric id); do not edit
 * by hand. Re-run the generator to refresh.
 *
 * Consumed by cbits/standard_surface.c for C_GetMechanismList /
 * C_GetMechanismInfo. CKF_* macros resolve against the pinned
 * spec/vendor headers at compile time.
 */
#ifndef HASKOKI_MECH_CATALOG_INC
#define HASKOKI_MECH_CATALOG_INC
"""


def real_tested_rows(mechs):
    """Rows the real engine executes, ascending by numeric id."""
    rows = [m for m in mechs if m.get("support", {}).get("real") == "tested"]
    return sorted(rows, key=lambda m: int(m["numeric_id"], 16))


def flag_expr(flags):
    """C flag expression for a mechanism_info.flags list."""
    if not flags:
        return "0UL"
    return "(unsigned long)(" + " | ".join(flags) + ")"


def render_inc(rows):
    """Render the catalog include text for real-tested rows."""
    lines = [HEADER.rstrip("\n"), "",
             f"#define HASKOKI_MECH_COUNT {len(rows)}", "",
             "struct haskoki_mech_row {",
             "  unsigned long id;",
             "  unsigned long min_key;",
             "  unsigned long max_key;",
             "  unsigned long flags;",
             "};", "",
             "static const struct haskoki_mech_row",
             "    haskoki_mech_catalog[HASKOKI_MECH_COUNT] = {"]
    for m in rows:
        mi = m["mechanism_info"]
        lines.append(
            f"  {{ 0x{int(m['numeric_id'], 16):08X}UL, "
            f"{mi['min_key_size']}UL, {mi['max_key_size']}UL, "
            f"{flag_expr(mi['flags'])} }}, /* {m['canonical_name']} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* HASKOKI_MECH_CATALOG_INC */")
    return "\n".join(lines) + "\n"


def expected_inc_text():
    """Render the expected include from the current JSON catalog."""
    data = json.loads(MECH_PATH.read_text())
    return render_inc(real_tested_rows(data["mechanisms"]))
