#!/usr/bin/env python3
"""Regenerate docs/coverage.md from the spec data.

Reads spec/mechanisms.json + spec/source-issues.json ONLY (no new claims
beyond evidence), asserts internal consistency, and writes the coverage /
limitations / source-issues publication. Usage:

  scripts/publish-coverage.py          # regenerate docs/coverage.md
  scripts/publish-coverage.py --check  # fail if docs/coverage.md is stale

Exit status: 0 iff generated output matches the committed doc (--check)
or was written successfully.
"""

import collections
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MECH = ROOT / "spec" / "mechanisms.json"
ISSUES = ROOT / "spec" / "source-issues.json"
OUT = ROOT / "docs" / "coverage.md"

BOUNDARY = """\
> Release-scope boundary (the original one-mechanism note is retired):
> every "tested" row below is proven IN-PROCESS by the
> Haskell suites (see test_evidence artifacts) against real
> libcrypto (pinned OpenSSL 4.0.2) and/or the synthetic engine.
> The C function tables of THIS release route real crypto over
> the 109-row tested catalog (see docs/demo-walkthrough.md §5 and
> scripts/test-release-install.sh); genuinely unsupported calls
> keep their documented refusals. No row below claims more than
> its evidence. Consumer evidence: scripts/test-consumers.sh,
> scripts/test-proxy-parity.sh, plus the 2026-09-21 consumer session notes (working notes, outside this package).
"""

LIMITATIONS_FIXED = """\
- C surface: the default config serves 1 slot with its token (a
  `[tokens]` catalog serves N slots; see SUPPORTED-HOSTS.md and
  `docs/demo-walkthrough.md` §8). Real C-surface crypto routes
  over the 109-row tested catalog; genuinely unsupported calls
  keep their documented refusals.
- `haskoki-ctl scenario run` simulates against an owned in-memory
  model; it never controls another live process.
- No certification, FIPS, Common Criteria, or production-security
  claim is made anywhere in this release.
"""


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def load():
    mechs = json.loads(MECH.read_text())["mechanisms"]
    issues = json.loads(ISSUES.read_text())["issues"]
    return mechs, issues


def check_consistency(mechs):
    total = len(mechs)
    assert total == 464, f"denominator drift: {total} rows, want the 464 catalog rows"
    ids = [r["numeric_id"] for r in mechs]
    assert len(set(ids)) == total, "duplicate numeric_id"
    n_alias = sum(len(r["aliases"]) for r in mechs)
    assert total + n_alias == 480, (
        f"header denominator drift: {total}+{n_alias}, want 480")
    for col in ("behavior", "real", "synthetic"):
        states = collections.Counter(r["support"][col] for r in mechs)
        assert sum(states.values()) == total, f"{col} counts do not sum"
    for r in mechs:
        b = r["support"]["behavior"]
        if b == "tested":
            assert r["test_evidence"], f"{r['canonical_name']}: tested without evidence"
        if b in ("unsupported-with-reason", "not-applicable"):
            assert r["notes"].strip(), f"{r['canonical_name']}: {b} without reason"
        if b == "planned":
            assert not r["test_evidence"], (
                f"{r['canonical_name']}: planned row carries evidence")


def fmt_counts(counter, total):
    order = ["tested", "unsupported-with-reason", "not-applicable", "planned"]
    return ", ".join(f"{counter.get(k, 0)} {k}" for k in order
                     if counter.get(k, 0)) + f" ({total} total)"


def render(mechs, issues):
    total = len(mechs)
    n_alias = sum(len(r["aliases"]) for r in mechs)
    by_beh = collections.Counter(r["support"]["behavior"] for r in mechs)
    by_real = collections.Counter(r["support"]["real"] for r in mechs)
    by_syn = collections.Counter(r["support"]["synthetic"] for r in mechs)
    fams = collections.defaultdict(lambda: collections.Counter())
    for r in mechs:
        fams[r["family"]][r["support"]["behavior"]] += 1

    L = []
    L.append("# Coverage, limitations and source issues")
    L.append("")
    L.append("GENERATED by scripts/publish-coverage.py — DO NOT EDIT.")
    L.append(f"Sources: spec/mechanisms.json (sha {sha(MECH)}), "
             f"spec/source-issues.json (sha {sha(ISSUES)}).")
    L.append("Denominator: 464 catalog rows "
             f"(+ {n_alias} aliases = 480 header CKM).")
    L.append("")
    L.append(BOUNDARY)
    L.append("## Mechanism coverage")
    L.append("")
    L.append(f"- behavior: {fmt_counts(by_beh, total)}")
    L.append(f"- real (libcrypto): {fmt_counts(by_real, total)}")
    L.append(f"- synthetic: {fmt_counts(by_syn, total)}")
    L.append("")
    L.append("Tested behavior rows carry `test_evidence` (suite/case ids); "
             "every unsupported/not-applicable row carries its reason in "
             "the row notes; planned rows carry no evidence (asserted by "
             "the publisher).")
    # The reporting closure, enumerated from the source of
    # truth (never from what's present): every suite named by any
    # test_evidence artifact. A suite dropped from evidence (or
    # from the build) changes this line loudly via --check.
    suites = sorted({e["artifact"].split("/")[0]
                     for r in mechs for e in r["test_evidence"]})
    n_ev = sum(len(r["test_evidence"]) for r in mechs)
    n_tested = len([r for r in mechs
                    if r["support"]["behavior"] == "tested"])
    L.append(f"Evidence suites: {', '.join(suites)} "
             f"({n_ev} evidence entries over {n_tested} tested rows).")
    L.append("")
    L.append("### By family (behavior column)")
    L.append("")
    L.append("| family | tested | unsupported | n/a | planned | total |")
    L.append("|---|---|---|---|---|---|")
    for fam in sorted(fams):
        c = fams[fam]
        L.append(f"| {fam} | {c.get('tested', 0)} | "
                 f"{c.get('unsupported-with-reason', 0)} | "
                 f"{c.get('not-applicable', 0)} | {c.get('planned', 0)} | "
                 f"{sum(c.values())} |")
    L.append("")
    L.append("### Behavior-tested mechanisms (executable recipes, in-process)")
    L.append("")
    L.append("Each row names its evidence artifacts (suite/case). No row "
             "implies C-surface availability (see boundary above).")
    L.append("")
    L.append("| mechanism | id | evidence cases |")
    L.append("|---|---|---|")
    tested = sorted((r for r in mechs if r["support"]["behavior"] == "tested"),
                    key=lambda r: int(r["numeric_id"], 16))
    for r in tested:
        ev = ", ".join(f"{e['artifact'].split('/')[-1]}:{e['case_id']}"
                       for e in r["test_evidence"][:4])
        if len(r["test_evidence"]) > 4:
            ev += f" (+{len(r['test_evidence']) - 4})"
        L.append(f"| {r['canonical_name']} | {r['numeric_id']} | {ev} |")
    L.append("")
    L.append("## Known limitations (from unsupported-with-reason rows)")
    L.append("")
    L.append("The behavior column's unsupported/not-applicable rows, with "
             "their recorded reasons (first line of row notes):")
    L.append("")
    L.append("| mechanism | id | disposition | reason |")
    L.append("|---|---|---|---|")
    lim = sorted((r for r in mechs
                  if r["support"]["behavior"] in
                  ("unsupported-with-reason", "not-applicable")),
                 key=lambda r: int(r["numeric_id"], 16))
    for r in lim:
        reason = r["notes"].strip().splitlines()[0][:160]
        reason = reason.replace("|", "/")
        L.append(f"| {r['canonical_name']} | {r['numeric_id']} | "
                 f"{r['support']['behavior']} | {reason} |")
    L.append("")
    L.append("Release-wide limitations (reviewed, non-generated):")
    L.append("")
    L.append(LIMITATIONS_FIXED)
    L.append("## Source issues")
    L.append("")
    L.append(f"{len(issues)} open issues in spec/source-issues.json:")
    L.append("")
    L.append("| id | title | status |")
    L.append("|---|---|---|")
    for i in issues:
        iid = i.get("id", "?")
        title = str(i.get("title", i.get("summary", "?")))[:120].replace("|", "/")
        status = str(i.get("status", "?"))
        L.append(f"| {iid} | {title} | {status} |")
    L.append("")
    return "\n".join(L)


def main():
    check = len(sys.argv) > 1 and sys.argv[1] == "--check"
    if len(sys.argv) > 1 and not check:
        print("usage: scripts/publish-coverage.py [--check]", file=sys.stderr)
        return 2
    mechs, issues = load()
    try:
        check_consistency(mechs)
    except AssertionError as e:
        print(f"FAIL: coverage data inconsistent: {e}", file=sys.stderr)
        return 1
    text = render(mechs, issues)
    if check:
        if not OUT.exists():
            print(f"FAIL: {OUT.relative_to(ROOT)} missing "
                  "(run: scripts/publish-coverage.py)", file=sys.stderr)
            return 1
        if OUT.read_text() != text:
            print(f"FAIL: {OUT.relative_to(ROOT)} stale "
                  "(run: scripts/publish-coverage.py)", file=sys.stderr)
            return 1
        print(f"coverage publication current "
              f"({len(mechs)} rows, {len(issues)} issues)")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} "
          f"({len(mechs)} rows, {len(issues)} issues)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
