{- | Generated attribute inventory and template rules.

GENERATED by @scripts/generate-attributes.py@ from the byte-locked
headers (identity) and the reviewed @TEMPLATE_RULES@ table (rules); do
not edit by hand. Re-run the generator to refresh.

Class, key-type and attribute rows carry numeric ids so production
code never hand-types them; 'Haskoki.Object.checkRules' enforces
'generatedTemplateRules' at the strict keygen/pairgen template paths.
The attribute inventory lets the standard-surface FFI resolve
caller @CKA_*@ ids to names without hand-typed numerics.
-}
{-# LANGUAGE OverloadedStrings #-}
module Haskoki.Attribute.Generated
  ( generatedAttributes
  , generatedClasses
  , generatedKeyTypes
  , generatedTemplateRules
  , attributeIdByName
  , attributeNameById
  , classIdByName
  , keyTypeIdByName
  , classNameById
  , keyTypeNameById
  , mustClassId
  , mustKeyTypeId
  ) where

import Data.Text (Text)
import Data.Word (Word64)

-- | Attribute inventory: @(numeric id, canonical name, aliases)@.
generatedAttributes :: [(Word64, Text, [Text])]
generatedAttributes =
  [ (0x0, "CKA_CLASS", [])
  , (0x1, "CKA_TOKEN", [])
  , (0x2, "CKA_PRIVATE", [])
  , (0x3, "CKA_LABEL", [])
  , (0x4, "CKA_UNIQUE_ID", [])
  , (0x10, "CKA_APPLICATION", [])
  , (0x11, "CKA_VALUE", [])
  , (0x12, "CKA_OBJECT_ID", [])
  , (0x80, "CKA_CERTIFICATE_TYPE", [])
  , (0x81, "CKA_ISSUER", [])
  , (0x82, "CKA_SERIAL_NUMBER", [])
  , (0x83, "CKA_AC_ISSUER", [])
  , (0x84, "CKA_OWNER", [])
  , (0x85, "CKA_ATTR_TYPES", [])
  , (0x86, "CKA_TRUSTED", [])
  , (0x87, "CKA_CERTIFICATE_CATEGORY", [])
  , (0x88, "CKA_JAVA_MIDP_SECURITY_DOMAIN", [])
  , (0x89, "CKA_URL", [])
  , (0x8a, "CKA_HASH_OF_SUBJECT_PUBLIC_KEY", [])
  , (0x8b, "CKA_HASH_OF_ISSUER_PUBLIC_KEY", [])
  , (0x8c, "CKA_NAME_HASH_ALGORITHM", [])
  , (0x90, "CKA_CHECK_VALUE", [])
  , (0x100, "CKA_KEY_TYPE", [])
  , (0x101, "CKA_SUBJECT", [])
  , (0x102, "CKA_ID", [])
  , (0x103, "CKA_SENSITIVE", [])
  , (0x104, "CKA_ENCRYPT", [])
  , (0x105, "CKA_DECRYPT", [])
  , (0x106, "CKA_WRAP", [])
  , (0x107, "CKA_UNWRAP", [])
  , (0x108, "CKA_SIGN", [])
  , (0x109, "CKA_SIGN_RECOVER", [])
  , (0x10a, "CKA_VERIFY", [])
  , (0x10b, "CKA_VERIFY_RECOVER", [])
  , (0x10c, "CKA_DERIVE", [])
  , (0x110, "CKA_START_DATE", [])
  , (0x111, "CKA_END_DATE", [])
  , (0x120, "CKA_MODULUS", [])
  , (0x121, "CKA_MODULUS_BITS", [])
  , (0x122, "CKA_PUBLIC_EXPONENT", [])
  , (0x123, "CKA_PRIVATE_EXPONENT", [])
  , (0x124, "CKA_PRIME_1", [])
  , (0x125, "CKA_PRIME_2", [])
  , (0x126, "CKA_EXPONENT_1", [])
  , (0x127, "CKA_EXPONENT_2", [])
  , (0x128, "CKA_COEFFICIENT", [])
  , (0x129, "CKA_PUBLIC_KEY_INFO", [])
  , (0x130, "CKA_PRIME", [])
  , (0x131, "CKA_SUBPRIME", [])
  , (0x132, "CKA_BASE", [])
  , (0x133, "CKA_PRIME_BITS", [])
  , (0x134, "CKA_SUBPRIME_BITS", ["CKA_SUB_PRIME_BITS"])
  , (0x160, "CKA_VALUE_BITS", [])
  , (0x161, "CKA_VALUE_LEN", [])
  , (0x162, "CKA_EXTRACTABLE", [])
  , (0x163, "CKA_LOCAL", [])
  , (0x164, "CKA_NEVER_EXTRACTABLE", [])
  , (0x165, "CKA_ALWAYS_SENSITIVE", [])
  , (0x166, "CKA_KEY_GEN_MECHANISM", [])
  , (0x170, "CKA_MODIFIABLE", [])
  , (0x171, "CKA_COPYABLE", [])
  , (0x172, "CKA_DESTROYABLE", [])
  , (0x180, "CKA_EC_PARAMS", ["CKA_ECDSA_PARAMS"])
  , (0x181, "CKA_EC_POINT", [])
  , (0x200, "CKA_SECONDARY_AUTH", [])
  , (0x201, "CKA_AUTH_PIN_FLAGS", [])
  , (0x202, "CKA_ALWAYS_AUTHENTICATE", [])
  , (0x210, "CKA_WRAP_WITH_TRUSTED", [])
  , (0x220, "CKA_OTP_FORMAT", [])
  , (0x221, "CKA_OTP_LENGTH", [])
  , (0x222, "CKA_OTP_TIME_INTERVAL", [])
  , (0x223, "CKA_OTP_USER_FRIENDLY_MODE", [])
  , (0x224, "CKA_OTP_CHALLENGE_REQUIREMENT", [])
  , (0x225, "CKA_OTP_TIME_REQUIREMENT", [])
  , (0x226, "CKA_OTP_COUNTER_REQUIREMENT", [])
  , (0x227, "CKA_OTP_PIN_REQUIREMENT", [])
  , (0x22a, "CKA_OTP_USER_IDENTIFIER", [])
  , (0x22b, "CKA_OTP_SERVICE_IDENTIFIER", [])
  , (0x22c, "CKA_OTP_SERVICE_LOGO", [])
  , (0x22d, "CKA_OTP_SERVICE_LOGO_TYPE", [])
  , (0x22e, "CKA_OTP_COUNTER", [])
  , (0x22f, "CKA_OTP_TIME", [])
  , (0x250, "CKA_GOSTR3410_PARAMS", [])
  , (0x251, "CKA_GOSTR3411_PARAMS", [])
  , (0x252, "CKA_GOST28147_PARAMS", [])
  , (0x300, "CKA_HW_FEATURE_TYPE", [])
  , (0x301, "CKA_RESET_ON_INIT", [])
  , (0x302, "CKA_HAS_RESET", [])
  , (0x400, "CKA_PIXEL_X", [])
  , (0x401, "CKA_PIXEL_Y", [])
  , (0x402, "CKA_RESOLUTION", [])
  , (0x403, "CKA_CHAR_ROWS", [])
  , (0x404, "CKA_CHAR_COLUMNS", [])
  , (0x405, "CKA_COLOR", [])
  , (0x406, "CKA_BITS_PER_PIXEL", [])
  , (0x480, "CKA_CHAR_SETS", [])
  , (0x481, "CKA_ENCODING_METHODS", [])
  , (0x482, "CKA_MIME_TYPES", [])
  , (0x500, "CKA_MECHANISM_TYPE", [])
  , (0x501, "CKA_REQUIRED_CMS_ATTRIBUTES", [])
  , (0x502, "CKA_DEFAULT_CMS_ATTRIBUTES", [])
  , (0x503, "CKA_SUPPORTED_CMS_ATTRIBUTES", [])
  , (0x601, "CKA_PROFILE_ID", [])
  , (0x602, "CKA_X2RATCHET_BAG", [])
  , (0x603, "CKA_X2RATCHET_BAGSIZE", [])
  , (0x604, "CKA_X2RATCHET_BOBS1STMSG", [])
  , (0x605, "CKA_X2RATCHET_CKR", [])
  , (0x606, "CKA_X2RATCHET_CKS", [])
  , (0x607, "CKA_X2RATCHET_DHP", [])
  , (0x608, "CKA_X2RATCHET_DHR", [])
  , (0x609, "CKA_X2RATCHET_DHS", [])
  , (0x60a, "CKA_X2RATCHET_HKR", [])
  , (0x60b, "CKA_X2RATCHET_HKS", [])
  , (0x60c, "CKA_X2RATCHET_ISALICE", [])
  , (0x60d, "CKA_X2RATCHET_NHKR", [])
  , (0x60e, "CKA_X2RATCHET_NHKS", [])
  , (0x60f, "CKA_X2RATCHET_NR", [])
  , (0x610, "CKA_X2RATCHET_NS", [])
  , (0x611, "CKA_X2RATCHET_PNS", [])
  , (0x612, "CKA_X2RATCHET_RK", [])
  , (0x617, "CKA_HSS_LEVELS", [])
  , (0x618, "CKA_HSS_LMS_TYPE", [])
  , (0x619, "CKA_HSS_LMOTS_TYPE", [])
  , (0x61a, "CKA_HSS_LMS_TYPES", [])
  , (0x61b, "CKA_HSS_LMOTS_TYPES", [])
  , (0x61c, "CKA_HSS_KEYS_REMAINING", [])
  , (0x61d, "CKA_PARAMETER_SET", [])
  , (0x61e, "CKA_OBJECT_VALIDATION_FLAGS", [])
  , (0x61f, "CKA_VALIDATION_TYPE", [])
  , (0x620, "CKA_VALIDATION_VERSION", [])
  , (0x621, "CKA_VALIDATION_LEVEL", [])
  , (0x622, "CKA_VALIDATION_MODULE_ID", [])
  , (0x623, "CKA_VALIDATION_FLAG", [])
  , (0x624, "CKA_VALIDATION_AUTHORITY_TYPE", [])
  , (0x625, "CKA_VALIDATION_COUNTRY", [])
  , (0x626, "CKA_VALIDATION_CERTIFICATE_IDENTIFIER", [])
  , (0x627, "CKA_VALIDATION_CERTIFICATE_URI", [])
  , (0x628, "CKA_VALIDATION_VENDOR_URI", [])
  , (0x629, "CKA_VALIDATION_PROFILE", [])
  , (0x62a, "CKA_ENCAPSULATE_TEMPLATE", [])
  , (0x62b, "CKA_DECAPSULATE_TEMPLATE", [])
  , (0x62c, "CKA_TRUST_SERVER_AUTH", [])
  , (0x62d, "CKA_TRUST_CLIENT_AUTH", [])
  , (0x62e, "CKA_TRUST_CODE_SIGNING", [])
  , (0x62f, "CKA_TRUST_EMAIL_PROTECTION", [])
  , (0x630, "CKA_TRUST_IPSEC_IKE", [])
  , (0x631, "CKA_TRUST_TIME_STAMPING", [])
  , (0x632, "CKA_TRUST_OCSP_SIGNING", [])
  , (0x633, "CKA_ENCAPSULATE", [])
  , (0x634, "CKA_DECAPSULATE", [])
  , (0x635, "CKA_HASH_OF_CERTIFICATE", [])
  , (0x636, "CKA_PUBLIC_CRC64_VALUE", [])
  , (0x637, "CKA_SEED", [])
  , (0x40000211, "CKA_WRAP_TEMPLATE", [])
  , (0x40000212, "CKA_UNWRAP_TEMPLATE", [])
  , (0x40000213, "CKA_DERIVE_TEMPLATE", [])
  , (0x40000600, "CKA_ALLOWED_MECHANISMS", [])
  , (0x80000000, "CKA_VENDOR_DEFINED", [])
  ]

-- | Class inventory: @(numeric id, canonical name, aliases)@.
generatedClasses :: [(Word64, Text, [Text])]
generatedClasses =
  [ (0x0, "CKO_DATA", [])
  , (0x1, "CKO_CERTIFICATE", [])
  , (0x2, "CKO_PUBLIC_KEY", [])
  , (0x3, "CKO_PRIVATE_KEY", [])
  , (0x4, "CKO_SECRET_KEY", [])
  , (0x5, "CKO_HW_FEATURE", [])
  , (0x6, "CKO_DOMAIN_PARAMETERS", [])
  , (0x7, "CKO_MECHANISM", [])
  , (0x8, "CKO_OTP_KEY", [])
  , (0x9, "CKO_PROFILE", [])
  , (0xa, "CKO_VALIDATION", [])
  , (0xb, "CKO_TRUST", [])
  , (0x80000000, "CKO_VENDOR_DEFINED", [])
  ]

-- | Key-type inventory: @(numeric id, canonical name, aliases)@.
generatedKeyTypes :: [(Word64, Text, [Text])]
generatedKeyTypes =
  [ (0x0, "CKK_RSA", [])
  , (0x1, "CKK_DSA", [])
  , (0x2, "CKK_DH", [])
  , (0x3, "CKK_EC", ["CKK_ECDSA"])
  , (0x4, "CKK_X9_42_DH", [])
  , (0x5, "CKK_KEA", [])
  , (0x10, "CKK_GENERIC_SECRET", [])
  , (0x11, "CKK_RC2", [])
  , (0x12, "CKK_RC4", [])
  , (0x13, "CKK_DES", [])
  , (0x14, "CKK_DES2", [])
  , (0x15, "CKK_DES3", [])
  , (0x16, "CKK_CAST", [])
  , (0x17, "CKK_CAST3", [])
  , (0x18, "CKK_CAST128", ["CKK_CAST5"])
  , (0x19, "CKK_RC5", [])
  , (0x1a, "CKK_IDEA", [])
  , (0x1b, "CKK_SKIPJACK", [])
  , (0x1c, "CKK_BATON", [])
  , (0x1d, "CKK_JUNIPER", [])
  , (0x1e, "CKK_CDMF", [])
  , (0x1f, "CKK_AES", [])
  , (0x20, "CKK_BLOWFISH", [])
  , (0x21, "CKK_TWOFISH", [])
  , (0x22, "CKK_SECURID", [])
  , (0x23, "CKK_HOTP", [])
  , (0x24, "CKK_ACTI", [])
  , (0x25, "CKK_CAMELLIA", [])
  , (0x26, "CKK_ARIA", [])
  , (0x27, "CKK_MD5_HMAC", [])
  , (0x28, "CKK_SHA_1_HMAC", [])
  , (0x29, "CKK_RIPEMD128_HMAC", [])
  , (0x2a, "CKK_RIPEMD160_HMAC", [])
  , (0x2b, "CKK_SHA256_HMAC", [])
  , (0x2c, "CKK_SHA384_HMAC", [])
  , (0x2d, "CKK_SHA512_HMAC", [])
  , (0x2e, "CKK_SHA224_HMAC", [])
  , (0x2f, "CKK_SEED", [])
  , (0x30, "CKK_GOSTR3410", [])
  , (0x31, "CKK_GOSTR3411", [])
  , (0x32, "CKK_GOST28147", [])
  , (0x33, "CKK_CHACHA20", [])
  , (0x34, "CKK_POLY1305", [])
  , (0x35, "CKK_AES_XTS", [])
  , (0x36, "CKK_SHA3_224_HMAC", [])
  , (0x37, "CKK_SHA3_256_HMAC", [])
  , (0x38, "CKK_SHA3_384_HMAC", [])
  , (0x39, "CKK_SHA3_512_HMAC", [])
  , (0x3a, "CKK_BLAKE2B_160_HMAC", [])
  , (0x3b, "CKK_BLAKE2B_256_HMAC", [])
  , (0x3c, "CKK_BLAKE2B_384_HMAC", [])
  , (0x3d, "CKK_BLAKE2B_512_HMAC", [])
  , (0x3e, "CKK_SALSA20", [])
  , (0x3f, "CKK_X2RATCHET", [])
  , (0x40, "CKK_EC_EDWARDS", [])
  , (0x41, "CKK_EC_MONTGOMERY", [])
  , (0x42, "CKK_HKDF", [])
  , (0x43, "CKK_SHA512_224_HMAC", [])
  , (0x44, "CKK_SHA512_256_HMAC", [])
  , (0x45, "CKK_SHA512_T_HMAC", [])
  , (0x46, "CKK_HSS", [])
  , (0x47, "CKK_XMSS", [])
  , (0x48, "CKK_XMSSMT", [])
  , (0x49, "CKK_ML_KEM", [])
  , (0x4a, "CKK_ML_DSA", [])
  , (0x4b, "CKK_SLH_DSA", [])
  , (0x80000000, "CKK_VENDOR_DEFINED", [])
  ]

-- | Template rules: @(class, key type, required, forbidden)@.
generatedTemplateRules :: [(Text, Maybe Text, [Text], [Text])]
generatedTemplateRules =
  [ ("CKO_SECRET_KEY", Just "CKK_AES", ["CKA_CLASS", "CKA_VALUE_LEN"], [])
  , ("CKO_PUBLIC_KEY", Just "CKK_EC", ["CKA_CLASS", "CKA_EC_PARAMS"], [])
  , ("CKO_PUBLIC_KEY", Just "CKK_RSA", ["CKA_CLASS", "CKA_MODULUS_BITS"], [])
  , ("CKO_SECRET_KEY", Just "CKK_HOTP", ["CKA_CLASS", "CKA_VALUE_LEN"], [])
  ]

attributeIdByName :: Text -> Maybe Word64
attributeIdByName name = lookup name [(n, w) | (w, n, _) <- generatedAttributes]

attributeNameById :: Word64 -> Maybe Text
attributeNameById w = lookup w [(w', n) | (w', n, _) <- generatedAttributes]

classIdByName :: Text -> Maybe Word64
classIdByName name = lookup name [(n, w) | (w, n, _) <- generatedClasses]

keyTypeIdByName :: Text -> Maybe Word64
keyTypeIdByName name = lookup name [(n, w) | (w, n, _) <- generatedKeyTypes]

classNameById :: Word64 -> Maybe Text
classNameById w = lookup w [(w', n) | (w', n, _) <- generatedClasses]

keyTypeNameById :: Word64 -> Maybe Text
keyTypeNameById w = lookup w [(w', n) | (w', n, _) <- generatedKeyTypes]

mustClassId :: Text -> Word64
mustClassId name = case classIdByName name of
  Just w -> w
  Nothing -> error ("mustClassId: unknown " ++ show name)

mustKeyTypeId :: Text -> Word64
mustKeyTypeId name = case keyTypeIdByName name of
  Just w -> w
  Nothing -> error ("mustKeyTypeId: unknown " ++ show name)
